POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "mia",
  "number": "00"
}

###

POST https://phonebook-back-h9uf.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Nana Thequeen",
  "number": "34-6306900"
}